{% set name = "numdifftools" %}
{% set version = "0.9.40" %}
{% set sha256 = "940692fd795e47083fad481d93c432b7fa9378758b5681dfc73a65152abfcd57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
    - pytest-runner  # in setup_requires for some reason
  run:
    - python >=3.7
    - numpy >=1.9
    - scipy >=0.8
    - algopy >=0.4
    - statsmodels >=0.6

test:
  imports:
    - numdifftools
    - numdifftools.tests
  commands:
    - python -m numdifftools.tests.test_multicomplex

about:
  home: https://github.com/pbrod/numdifftools/
  summary: Solves automatic numerical differentiation problems in one or more variables.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: http://numdifftools.readthedocs.io/en/latest/
  dev_url: https://github.com/pbrod/numdifftools/

extra:
  recipe-maintainers:
    - giacomov
    - pbrod
    - djsutherland
