{% set name = "numdifftools" %}
{% set version = "0.9.38" %}
{% set sha256 = "8fae7b057087c27e3f8340f646aab3a80679d2f6efadacb37ece28a78a71f058" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  
requirements:
  build:
    - python
    - setuptools
    - pyscaffold <2.5  # doesn't build with older versions
  run:
    - python
    - setuptools  # the __init__ files use pkg_resources
    - numpy >=1.9
    - scipy >=0.8
    - algopy >=0.4

test:
  imports:
    - numdifftools
    - numdifftools.tests
  commands:
    - python -m numdifftools.tests.test_multicomplex

about:
  home: "https://github.com/pbrod/numdifftools/"
  summary: Solves automatic numerical differentiation problems in one or more variables.
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'  # https://github.com/pbrod/numdifftools/pull/35
  doc_url: http://numdifftools.readthedocs.io/en/latest/
  dev_url: https://github.com/pbrod/numdifftools/

extra:
  recipe-maintainers:
    - giacomov
    - pbrod
    - dougalsutherland
