{% set name = "numdifftools" %}
{% set version = "0.11.0" %}
{% set sha256 = "fa4d75ec44c49ea03805795838c20fd70c300e5de8fae28630447becb5f52d48" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Reset build number to 0 for a new version upload
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - scipy >=1.7.3

test:
  imports:
    - numdifftools
    - numdifftools.tests
  requires:
    - pip
    - pytest
    - pytest-cov
    - hypothesis
    - algopy >=0.4
    - statsmodels >=0.6
    - matplotlib-base >=3.8.0
  commands:
    - pip check
    - pytest --pyargs numdifftools

about:
  home: https://github.com/pbrod/numdifftools/
  summary: Solves automatic numerical differentiation problems in one or more variables.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://numdifftools.readthedocs.io/en/latest/
  dev_url: https://github.com/pbrod/numdifftools/

extra:
  recipe-maintainers:
    - Anselmoo
    - giacomov
    - pbrod
    - djsutherland
