{% set name = "numdifftools" %}
{% set version = "0.9.42" %}
{% set sha256 = "866675171f293c4bf2f1e1c5bf9b88a07d5396903e3b3e7fcc3879e2a01cfbc1" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Reset build number to 0 for a new version upload
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.21.2
    - scipy >=1.7.3

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-cov
    - numpy
    - scipy
    - algopy >=0.4
    - statsmodels >=0.6
    - matplotlib >=3.8.0
  imports:
    - numdifftools
    - numdifftools.tests
  commands:
    - pip check
    - python -m numdifftools.tests.test_multicomplex

about:
  home: https://github.com/pbrod/numdifftools/
  summary: Solves automatic numerical differentiation problems in one or more variables.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://numdifftools.readthedocs.io/en/latest/
  dev_url: https://github.com/pbrod/numdifftools/

extra:
  recipe-maintainers:
    - Anselmoo
    - giacomov
    - pbrod
    - djsutherland
